# Dictionary of tile sizes for each M
gpt3_mlp_v100 = {
  2048: {"TileSizes" : [[256, 256, 32, 128, 128, 32], [256, 256, 32, 128, 128, 32]],
    "baseline": {"split_ks": [1,1]},
    "rowsync": {"split_ks": [1,1]},
    "tilesync": {"split_ks": [1,1],
                "AvoidCustomOrder": False,
                "AvoidWaitKernel": False,
                "ReorderTileLoads": True,
                "NoAtomicAdd": True}
  },
  1024: {"TileSizes" : [[256, 256, 32, 128, 128, 32], [256, 256, 32, 128, 128, 32]],
    "baseline": {"split_ks": [2,1]},
    "rowsync": {"split_ks": [2,1]},
    "tilesync": {"split_ks": [2,1],
                "AvoidCustomOrder": False,
                "AvoidWaitKernel": False,
                "ReorderTileLoads": True,
                "NoAtomicAdd": True}
  },
  512: {"TileSizes" : [[256, 256, 32, 128, 128, 32], [256, 256, 32, 128, 128, 32]],
    "baseline": {"split_ks": [2,1]},
    "rowsync": {"split_ks": [2,1]},
    "tilesync": {"split_ks": [2,1],
                "AvoidCustomOrder": False,
                "AvoidWaitKernel": False,
                "ReorderTileLoads": True,
                "NoAtomicAdd": True}
  },
  256: {"TileSizes" : [[256, 128, 32, 128, 64, 32], [256, 128, 32, 128, 64, 32]],
    "baseline": {"split_ks": [4,2]},
    "rowsync": {"split_ks": [4,2],
                  "AvoidWaitKernel": True,
                  "AvoidCustomOrder": True},
    "tilesync": {"split_ks": [4,2],
                "AvoidCustomOrder": True,
                "AvoidWaitKernel": True,
                "ReorderTileLoads": True,
                "NoAtomicAdd": True}
  },
  128: {"TileSizes" : [[128, 256, 32, 64, 128, 32], [128, 256, 32, 64, 128, 32]],
    "baseline": {"split_ks": [3,3]},
    "rowsync": {"split_ks": [3,3],
                  "AvoidWaitKernel": True,
                  "AvoidCustomOrder": True},
    "tilesync": {"split_ks": [3,3],
                "AvoidCustomOrder": True,
                "AvoidWaitKernel": True,
                "ReorderTileLoads": True,
                "NoAtomicAdd": True}
  },
  64: {"TileSizes" : [[64, 256, 32, 32, 128, 32], [64, 256, 32, 32, 128, 32]],
    "baseline": {"split_ks": [6,3]},
    "rowsync": {"split_ks": [6,3],
                  "AvoidWaitKernel": True,
                  "AvoidCustomOrder": True},
    "tilesync": {"split_ks": [4,3],
                "AvoidCustomOrder": True,
                "AvoidWaitKernel": True,
                "ReorderTileLoads": True,
                "NoAtomicAdd": True}
  },
  32: {"TileSizes" : [[32, 256, 32, 32, 64, 32], [32, 128, 32, 32, 32, 32]],
    "baseline": {"split_ks": [4,3]},
    "rowsync": {"split_ks": [4,3],
                  "AvoidWaitKernel": True,
                  "AvoidCustomOrder": True},
    "tilesync": {"split_ks": [4,3],
                "TileBatchSync":2,
                "AvoidCustomOrder": True,
                "AvoidWaitKernel": True,
                "ReorderTileLoads": True,
                "NoAtomicAdd": True}
  },
  16: {"TileSizes" : [[32, 256, 32, 32, 64, 32], [32, 128, 32, 32, 32, 32]],
    "baseline": {"split_ks": [4,3]},
    "rowsync": {"split_ks": [4,3],
                  "AvoidWaitKernel": True,
                  "AvoidCustomOrder": True},
    "tilesync": {"split_ks": [4,3],
                "AvoidCustomOrder": True,
                "AvoidWaitKernel": True,
                "ReorderTileLoads": True,
                "NoAtomicAdd": True}
  },
  8: {"TileSizes" : [[32, 256, 32, 32, 64, 32], [32, 128, 32, 32, 32, 32]],
    "baseline": {"split_ks": [4,3]},
    "rowsync": {"split_ks": [4,3],
                  "AvoidWaitKernel": True,
                  "AvoidCustomOrder": True},
    "tilesync": {"split_ks": [4,3],
                  "AvoidCustomOrder": True,
                  "AvoidWaitKernel": True,
                  "ReorderTileLoads": True,
                  "NoAtomicAdd": True}
  },
  4: {"TileSizes" : [[32, 256, 32, 32, 64, 32], [32, 128, 32, 32, 32, 32]],
    "baseline": {"split_ks": [4,3]},
    "rowsync": {"split_ks": [4,3],
                  "AvoidWaitKernel": True,
                  "AvoidCustomOrder": True},
    "tilesync": {"split_ks": [4,3],
                "AvoidCustomOrder": True,
                "AvoidWaitKernel": True,
                "ReorderTileLoads": True,
                "NoAtomicAdd": True}
  },
  2: {"TileSizes" : [[32, 256, 32, 32, 64, 32], [32, 128, 32, 32, 32, 32]],
    "baseline": {"split_ks": [4,3]},
    "rowsync": {"split_ks": [4,3],
                  "AvoidWaitKernel": True,
                  "AvoidCustomOrder": True},
    "tilesync": {"split_ks": [4,3], 
                "AvoidCustomOrder": True,
                "AvoidWaitKernel": True,
                "ReorderTileLoads": True,
                "NoAtomicAdd": True}
  },
  1: {"TileSizes" : [[32, 256, 32, 32, 64, 32], [32, 128, 32, 32, 32, 32]],
    "baseline": {"split_ks": [4,3]},
    "rowsync": {"split_ks": [4,3],
                  "AvoidWaitKernel": True,
                  "AvoidCustomOrder": True},
    "tilesync": {"split_ks": [4,3],
                  "AvoidCustomOrder": True,
                  "AvoidWaitKernel": True,
                  "ReorderTileLoads": True,
                  "NoAtomicAdd": True},
  },
}

llama_mlp_v100 = {
  2048: {
    "TileSizes" : [[256, 256, 32, 128, 64, 32], [256, 256, 32, 128, 64, 32]],
    "baseline": {"split_ks": [3,1]},
    "rowsync": {"split_ks": [1,1]},
    "tilesync": {"split_ks": [1,1],
                "AvoidCustomOrder": False,
                "AvoidWaitKernel": False,
                "ReorderTileLoads": True,}
  },
  1024: {"TileSizes" : [[256, 256, 32, 128, 64, 32], [256, 256, 32, 128, 64, 32]],
    "baseline": {"split_ks": [2,1]},
    "rowsync": {"split_ks": [2,1]},
    "tilesync": {"split_ks": [2,1],
                "AvoidCustomOrder": False,
                "AvoidWaitKernel": False,
                "ReorderTileLoads": True,}
  },
  512: {"TileSizes" : [[256, 256, 32, 128, 64, 32], [256, 256, 32, 128, 64, 32]],
    "baseline": {"split_ks": [3,1]},
    "rowsync": {"split_ks": [2,1]},
    "tilesync": {"split_ks": [2,1],
                "AvoidCustomOrder": False,
                "AvoidWaitKernel": False,
                "ReorderTileLoads": True,}
  },
  256: {"TileSizes" : [[256, 128, 32, 128, 64, 32], [256, 128, 32, 128, 64, 32]],
    "baseline": {"split_ks": [6,4]},
    "rowsync": {"split_ks": [4,4], 
                "AvoidWaitKernel": True,
                "AvoidCustomOrder": True},
    "tilesync": {"split_ks": [4,4], "AvoidCustomOrder": True,
                                    "AvoidWaitKernel": True,
                                    "ReorderTileLoads": True},
  },
  128: {"TileSizes" : [[128, 128, 32, 64, 64, 32], [128, 128, 32, 64, 64, 32]],
    "baseline": {"split_ks": [8,2]},
    "rowsync": {"split_ks": [4,2], 
                  "AvoidWaitKernel": True,
                  "AvoidCustomOrder": True},
    "tilesync": {"split_ks": [4,2], "AvoidCustomOrder": True,
                                    "AvoidWaitKernel": True,
                                    "ReorderTileLoads": True},
  },
  64: {"TileSizes" : [[64, 128, 32, 32, 64, 32], [64, 128, 32, 32, 64, 32]],
    "baseline": {"split_ks": [8,8]},
    "rowsync": {"split_ks": [8,8],
                  "AvoidWaitKernel": True,
                  "AvoidCustomOrder": True},
    "tilesync": {"split_ks": [8,8], "AvoidCustomOrder": True,
                                    "AvoidWaitKernel": True,
                                    "ReorderTileLoads": True},
  },
  32: {"TileSizes" : [[32, 128, 32, 32, 32, 32], [32, 128, 32, 32, 32, 32]],
    "baseline": {"split_ks": [4,4]},
    "rowsync": {"split_ks": [4,4], 
                  "AvoidWaitKernel": True,
                  "AvoidCustomOrder": True},
    "tilesync": {"split_ks": [4,4], "AvoidCustomOrder": True,
                                    "AvoidWaitKernel": True,
                                    "ReorderTileLoads": True},
  },
  16: {"TileSizes" : [[32, 128, 32, 32, 32, 32], [32, 128, 32, 32, 32, 32]],
    "baseline": {"split_ks": [4,4]},
    "rowsync": {"split_ks": [4,4], 
                  "AvoidWaitKernel": True,
                  "AvoidCustomOrder": True},
    "tilesync": {"split_ks": [4,4], "AvoidCustomOrder": True,
                                    "AvoidWaitKernel": True,
                                    "ReorderTileLoads": True},
  },
  8: {"TileSizes" : [[32, 128, 32, 32, 32, 32], [32, 128, 32, 32, 32, 32]],
    "baseline": {"split_ks": [4,4]},
    "rowsync": {"split_ks": [4,4], 
                  "AvoidWaitKernel": True,
                  "AvoidCustomOrder": True},
    "tilesync": {"split_ks": [4,4], "AvoidCustomOrder": True,
                                    "AvoidWaitKernel": True,
                                    "ReorderTileLoads": True},
  },
  4: {"TileSizes" : [[32, 128, 32, 32, 32, 32], [32, 128, 32, 32, 32, 32]],
    "baseline": {"split_ks": [4,4]},
    "rowsync": {"split_ks": [4,4], 
                  "AvoidWaitKernel": True,
                  "AvoidCustomOrder": True},
    "tilesync": {"split_ks": [4,4], "AvoidCustomOrder": True,
                                    "AvoidWaitKernel": True,
                                    "ReorderTileLoads": True},
  },
  2: {"TileSizes" : [[32, 128, 32, 32, 32, 32], [32, 128, 32, 32, 32, 32]],
    "baseline": {"split_ks": [4,4]},
    "rowsync": {"split_ks": [4,4], 
                  "AvoidWaitKernel": True,
                  "AvoidCustomOrder": True},
    "tilesync": {"split_ks": [4,4], "AvoidCustomOrder": True,
                                    "AvoidWaitKernel": True,
                                    "ReorderTileLoads": True},
  },
  1: {"TileSizes" : [[32, 128, 32, 32, 32, 32], [32, 128, 32, 32, 32, 32]],
    "baseline": {"split_ks": [4,4]},
    "rowsync": {"split_ks": [4,4], 
                  "AvoidWaitKernel": True,
                  "AvoidCustomOrder": True},
    "tilesync": {"split_ks": [4,4], "AvoidCustomOrder": True,
                                    "AvoidWaitKernel": True,
                                    "ReorderTileLoads": True},
  },
}